#Connection to DB
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projet_mediaskol_formations
    username: root
    password: root

#Options to DB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create