#Connection to DB
spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3306/projet_mediaskol_formations
    username: root
    password: root

  #Options to DB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    # Comme la base est vide, pas besoin de baseliner
  flyway:
    baseline-on-migrate: false
    locations: classpath:db/migration

#i18n
  messages:
    encoding: UTF-8
  web:
    locale: fr

#jwt
app:
  jwt:
    secret: 436a726878792a6a2333725030382050303877505e30585b6351413978